theme: jekyll-theme-leap-day
description: A document going over the Safe Network API for developers. By Joseph Meagher
title: SAFE API Overview
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
